server:
  port: 8011    
 
spring:    
  application:
    name: product-service   
     
    
eureka:         
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
    hostname: eureka-0
  client:
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5   
        
