server:
  port: 8011    
 
spring:    
  application:
    name: product-service   
     
    
eureka:         
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5   
        
